[build.environment]
  NPM_FLAGS = "--version"

[build]
  publish = "dist"
  command = "npx pnpm i --store=node_modules/.pnpm-store && npm run build"

[[redirects]]
  from = "/posts/2021-08-08-vue-i18n-in-real-world-application"
  to = "/posts/vue-i18n-difficulties"
  status = 301
  force = true

[[redirects]]
  from = "/posts/vue-i18n-in-real-world-application"
  to = "/posts/vue-i18n-difficulties"
  status = 301
  force = true
